- .gitignore
- README.md
- data/addressbook.json
Let's
* Remove `/data/` from .gitignore to track the new sample data file
* Add sample data which is tailored to a contractor payroll management context
* Add the Codecov badge to `README.md`
> Resolve AY2122S2-CS2103T-T11-4/tp#11

- docs/AboutUs.md
Update username and reference to user image to match the correct username.
> Update AboutUs links

- docs/_config.yml
- docs/index.md
Remove traces of AB3 in config.yml. Update index.md to match README.md.
> Update config.yml and index.md to close v1.1

- src/main/java/seedu/address/model/job/Job.java
- src/main/java/seedu/address/model/job/Money.java
- src/test/java/seedu/address/model/job/JobTest.java
- src/test/java/seedu/address/model/job/MoneyTest.java
Add both Job and Money class as baseline implementation. Somewhat of placeholders first due to high dependency on Job class.
> Add Job class and Money class

- README.md
- docs/DeveloperGuide.md
- docs/index.md
Cosmetic fixes on our website and README
> Fix Whitespace and images

- .gitignore
Do we actually have to make new PRs for every change
> Update gitignore to remove vscode config

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
lol
what's there to fix
closes #21
> Update add/delete/edit commands

- src/main/java/seedu/address/model/job/Job.java
- src/main/java/seedu/address/model/job/Money.java
- src/main/java/seedu/address/model/job/Rate.java
- src/test/java/seedu/address/model/job/JobTest.java
- src/test/java/seedu/address/model/job/MoneyTest.java
> Refactor Job and Money classes to be more robust and flexible

- src/main/java/seedu/address/model/person/Email.java
- src/test/java/seedu/address/model/person/EmailTest.java
> Fix email regex to accept consecutive underscores and hyphens

- src/main/java/seedu/address/model/job/JobList.java
modeled after UniquePersonsList
> Add JobList Interface

- docs/DeveloperGuide.md
- src/main/java/peoplesoft/MainApp.java
- src/test/java/peoplesoft/logic/commands/FindCommandTest.java
> Updated DG

- docs/DeveloperGuide.md
- docs/diagrams/StorageClassDiagram.puml
(more details to be added in a tutorial; in the process of writing it now, but I realized that I'll probably need to do some slight refactoring to make things more uniform)
> Add info re: implementation of the serdes stuff

- docs/tutorials/WritingSerdesClasses.md
> Add tutorial for writing serializers/deserializers for model classes

- docs/UserGuide.md
- src/main/java/peoplesoft/MainApp.java
Update the mark command to reflect its actual functionality and also fix app version to v1.3
> Minor fix to app version and UG

- src/main/java/peoplesoft/logic/commands/EditCommand.java
- src/main/java/peoplesoft/logic/parser/AddCommandParser.java
- src/main/java/peoplesoft/model/job/exceptions/PaymentAlreadyPaidException.java
- src/main/java/peoplesoft/model/person/Payment.java
- src/main/java/peoplesoft/model/person/Person.java
- src/main/java/peoplesoft/model/util/SampleDataUtil.java
- src/test/java/peoplesoft/model/AddressBookSerdesTest.java
- src/test/java/peoplesoft/model/person/PersonSerdesTest.java
- src/test/java/peoplesoft/model/person/UniquePersonListSerdesTest.java
- src/test/java/peoplesoft/testutil/PersonBuilder.java
- src/test/java/peoplesoft/testutil/PersonUtil.java
still have to make `Job` use it though
closes #93
> Implement payment class

- docs/UserGuide.md
Also shifted around `help` and `exit`
> Update changes to the UG to include `pay`

- src/main/java/peoplesoft/logic/commands/job/JobAssignCommand.java
- src/main/java/peoplesoft/model/util/SampleDataUtil.java
Also potential fix for sample data `personIdState` issue (closes #127)
> Small fix for `assign` on marked `Job`s

- src/main/java/peoplesoft/logic/commands/EditCommand.java
> Fix `EditCommand` not working with `Rate`

- docs/UserGuide.md
I'm not sure if the command summary table has been resolved since I am unable to replicate the issue on my end, but no warning is thrown by the IDE, as was the case before the edits. Do let me know if it still has yet to be resolved!
> Address some of the identified UG bugs

- docs/UserGuide.md
Closes:
- #145
- #151
- #152 
- #180 
- #191
> UG fixes: low hanging fruit

- src/main/java/peoplesoft/ui/regions/PersonCard.java
> Force label tags to wrap

- src/main/java/peoplesoft/ui/scenes/HelpPage.java
> Avoid using Desktop.browse() on Linux

- docs/UserGuide.md
- src/main/java/peoplesoft/logic/commands/job/JobAssignCommand.java
- src/main/java/peoplesoft/logic/commands/job/JobFinalizeCommand.java
- src/main/java/peoplesoft/logic/commands/job/JobMarkCommand.java
- src/main/java/peoplesoft/logic/parser/ParserUtil.java
- src/main/java/peoplesoft/model/job/Job.java
- src/main/java/peoplesoft/model/job/util/MoneyUtil.java
- src/main/java/peoplesoft/model/money/Rate.java
- src/test/java/peoplesoft/logic/parser/ParserUtilTest.java
Closes #173, #174, #190, #197 
Adds the limits stated in #194
> Minor bug fixes for v1.4

- .githooks/pre-commit
- .githooks/pre-commit.d/fix-fxml-versions
- src/main/resources/view/HelpPage.fxml
- src/main/resources/view/JobListCard.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/OverviewPage.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/SideBar.fxml
git hook should automatically fix bad xmlns versions
closes #153
> Fix fxml JavaFX xmlns versions, hopefully permanently

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/tutorials/WritingSerdesClasses.md
- src/main/java/peoplesoft/model/AddressBook.java
- src/main/java/peoplesoft/model/ModelManager.java
- src/main/java/peoplesoft/model/person/Person.java
- src/main/java/peoplesoft/model/person/UniquePersonList.java
- src/test/java/peoplesoft/model/AddressBookTest.java
- src/test/java/peoplesoft/model/ModelManagerTest.java
- src/test/java/peoplesoft/model/person/PersonTest.java
- src/test/java/peoplesoft/model/person/UniquePersonListTest.java
Simple fix to throw exception when adding duplicate employee (same data fields, even with different id) 
PR addresses issue #159
> Resolve addition of duplicate employees

- docs/team/ian-from-dover.md
- src/main/java/peoplesoft/ui/scenes/HelpPage.java
Really minor fix for Ian's PPP
> Fix formatting inconsistencies in Ian's PPP

- docs/DeveloperGuide.md
- src/main/java/peoplesoft/ui/scenes/HelpPage.java
- Flesh out some user stories
- Add captions to most images
- Otherwise minor edits here and there 
- (Not a DG update) Update HelpWindow to use its parameters
> Some DG updates

- docs/UserGuide.md
- docs/_config.yml
Also fixed our github link pointing to the wrong repository (it pointed to T11-3)
> Fix table of contents and command summary

- docs/UserGuide.md
> Minor fixes, add parameter constraints
